import getUnicodeFlagIcon from "country-flag-icons/unicode";

const COUNTRIES = [
  { code: "AL", name: "Albania", phoneCode: "+355", flag: getUnicodeFlagIcon("AL") },
  { code: "DE", name: "Alemania", phoneCode: "+49", flag: getUnicodeFlagIcon("DE") },
  { code: "AD", name: "Andorra", phoneCode: "+376", flag: getUnicodeFlagIcon("AD") },
  { code: "AM", name: "Armenia", phoneCode: "+374", flag: getUnicodeFlagIcon("AM") },
  { code: "AT", name: "Austria", phoneCode: "+43", flag: getUnicodeFlagIcon("AT") },
  { code: "AZ", name: "Azerbaiyán", phoneCode: "+994", flag: getUnicodeFlagIcon("AZ") },
  { code: "BE", name: "Bélgica", phoneCode: "+32", flag: getUnicodeFlagIcon("BE") },
  { code: "BY", name: "Bielorrusia", phoneCode: "+375", flag: getUnicodeFlagIcon("BY") },
  { code: "BA", name: "Bosnia y Herzegovina", phoneCode: "+387", flag: getUnicodeFlagIcon("BA") },
  { code: "BG", name: "Bulgaria", phoneCode: "+359", flag: getUnicodeFlagIcon("BG") },
  { code: "CY", name: "Chipre", phoneCode: "+357", flag: getUnicodeFlagIcon("CY") },
  { code: "VA", name: "Ciudad del Vaticano", phoneCode: "+39", flag: getUnicodeFlagIcon("VA") },
  { code: "HR", name: "Croacia", phoneCode: "+385", flag: getUnicodeFlagIcon("HR") },
  { code: "DK", name: "Dinamarca", phoneCode: "+45", flag: getUnicodeFlagIcon("DK") },
  { code: "SK", name: "Eslovaquia", phoneCode: "+421", flag: getUnicodeFlagIcon("SK") },
  { code: "SI", name: "Eslovenia", phoneCode: "+386", flag: getUnicodeFlagIcon("SI") },
  { code: "ES", name: "España", phoneCode: "+34", flag: getUnicodeFlagIcon("ES") },
  { code: "EE", name: "Estonia", phoneCode: "+372", flag: getUnicodeFlagIcon("EE") },
  { code: "FI", name: "Finlandia", phoneCode: "+358", flag: getUnicodeFlagIcon("FI") },
  { code: "FR", name: "Francia", phoneCode: "+33", flag: getUnicodeFlagIcon("FR") },
  { code: "GE", name: "Georgia", phoneCode: "+995", flag: getUnicodeFlagIcon("GE") },
  { code: "GR", name: "Grecia", phoneCode: "+30", flag: getUnicodeFlagIcon("GR") },
  { code: "HU", name: "Hungría", phoneCode: "+36", flag: getUnicodeFlagIcon("HU") },
  { code: "IE", name: "Irlanda", phoneCode: "+353", flag: getUnicodeFlagIcon("IE") },
  { code: "IS", name: "Islandia", phoneCode: "+354", flag: getUnicodeFlagIcon("IS") },
  { code: "FO", name: "Islas Feroe", phoneCode: "+298", flag: getUnicodeFlagIcon("FO") },
  { code: "IT", name: "Italia", phoneCode: "+39", flag: getUnicodeFlagIcon("IT") },
  { code: "XK", name: "Kosovo", phoneCode: "+383", flag: getUnicodeFlagIcon("XK") },
  { code: "LV", name: "Letonia", phoneCode: "+371", flag: getUnicodeFlagIcon("LV") },
  { code: "LI", name: "Liechtenstein", phoneCode: "+423", flag: getUnicodeFlagIcon("LI") },
  { code: "LT", name: "Lituania", phoneCode: "+370", flag: getUnicodeFlagIcon("LT") },
  { code: "LU", name: "Luxemburgo", phoneCode: "+352", flag: getUnicodeFlagIcon("LU") },
  { code: "MK", name: "Macedonia del Norte", phoneCode: "+389", flag: getUnicodeFlagIcon("MK") },
  { code: "MT", name: "Malta", phoneCode: "+356", flag: getUnicodeFlagIcon("MT") },
  { code: "MD", name: "Moldavia", phoneCode: "+373", flag: getUnicodeFlagIcon("MD") },
  { code: "MC", name: "Mónaco", phoneCode: "+377", flag: getUnicodeFlagIcon("MC") },
  { code: "ME", name: "Montenegro", phoneCode: "+382", flag: getUnicodeFlagIcon("ME") },
  { code: "NO", name: "Noruega", phoneCode: "+47", flag: getUnicodeFlagIcon("NO") },
  { code: "NL", name: "Países Bajos", phoneCode: "+31", flag: getUnicodeFlagIcon("NL") },
  { code: "PL", name: "Polonia", phoneCode: "+48", flag: getUnicodeFlagIcon("PL") },
  { code: "PT", name: "Portugal", phoneCode: "+351", flag: getUnicodeFlagIcon("PT") },
  { code: "GB", name: "Reino Unido", phoneCode: "+44", flag: getUnicodeFlagIcon("GB") },
  { code: "CZ", name: "República Checa", phoneCode: "+420", flag: getUnicodeFlagIcon("CZ") },
  { code: "RO", name: "Rumanía", phoneCode: "+40", flag: getUnicodeFlagIcon("RO") },
  { code: "RU", name: "Rusia", phoneCode: "+7", flag: getUnicodeFlagIcon("RU") },
  { code: "SM", name: "San Marino", phoneCode: "+378", flag: getUnicodeFlagIcon("SM") },
  { code: "SE", name: "Suecia", phoneCode: "+46", flag: getUnicodeFlagIcon("SE") },
  { code: "CH", name: "Suiza", phoneCode: "+41", flag: getUnicodeFlagIcon("CH") },
  { code: "TR", name: "Turquía", phoneCode: "+90", flag: getUnicodeFlagIcon("TR") },
  { code: "UA", name: "Ucrania", phoneCode: "+380", flag: getUnicodeFlagIcon("UA") },
  { code: "AR", name: "Argentina", phoneCode: "+54", flag: getUnicodeFlagIcon("AR") },
  { code: "BR", name: "Brasil", phoneCode: "+55", flag: getUnicodeFlagIcon("BR") },
  { code: "CA", name: "Canadá", phoneCode: "+1", flag: getUnicodeFlagIcon("CA") },
  { code: "CL", name: "Chile", phoneCode: "+56", flag: getUnicodeFlagIcon("CL") },
  { code: "CO", name: "Colombia", phoneCode: "+57", flag: getUnicodeFlagIcon("CO") },
  { code: "CR", name: "Costa Rica", phoneCode: "+506", flag: getUnicodeFlagIcon("CR") },
  { code: "CU", name: "Cuba", phoneCode: "+53", flag: getUnicodeFlagIcon("CU") },
  { code: "EC", name: "Ecuador", phoneCode: "+593", flag: getUnicodeFlagIcon("EC") },
  { code: "SV", name: "El Salvador", phoneCode: "+503", flag: getUnicodeFlagIcon("SV") },
  { code: "US", name: "Estados Unidos", phoneCode: "+1", flag: getUnicodeFlagIcon("US") },
  { code: "MX", name: "México", phoneCode: "+52", flag: getUnicodeFlagIcon("MX") },
  { code: "PA", name: "Panamá", phoneCode: "+507", flag: getUnicodeFlagIcon("PA") },
  { code: "PY", name: "Paraguay", phoneCode: "+595", flag: getUnicodeFlagIcon("PY") },
  { code: "PE", name: "Perú", phoneCode: "+51", flag: getUnicodeFlagIcon("PE") },
  { code: "UY", name: "Uruguay", phoneCode: "+598", flag: getUnicodeFlagIcon("UY") },
  { code: "VE", name: "Venezuela", phoneCode: "+58", flag: getUnicodeFlagIcon("VE") },
  { code: "CN", name: "China", phoneCode: "+86", flag: getUnicodeFlagIcon("CN") },
  { code: "IN", name: "India", phoneCode: "+91", flag: getUnicodeFlagIcon("IN") },
  { code: "JP", name: "Japón", phoneCode: "+81", flag: getUnicodeFlagIcon("JP") },
  { code: "AU", name: "Australia", phoneCode: "+61", flag: getUnicodeFlagIcon("AU") },
  { code: "ZA", name: "Sudáfrica", phoneCode: "+27", flag: getUnicodeFlagIcon("ZA") },
].sort((a, b) => a.name.localeCompare(b.name));

export const SPAIN = {
  code: "ES",
  name: "España",
  phoneCode: "+34",
  flag: getUnicodeFlagIcon("ES"),
};

export default COUNTRIES;
