export const months = [
    { name: "Enero", value: 1 },
    { name: "Febrero", value: 2 },
    { name: "Marzo", value: 3 },
    { name: "Abril", value: 4 },
    { name: "Mayo", value: 5 },
    { name: "Junio", value: 6 },
    { name: "Julio", value: 7 },
    { name: "Agosto", value: 8 },
    { name: "Sptiembre", value: 9 },
    { name: "Octubre", value: 10 },
    { name: "Noviembre", value: 11 },
    { name: "Diciembre", value: 12 },
  ];
  
  export const autonomousCommunities = [
    { name: "Andalucía", value: "AND" },
    { name: "Aragón", value: "ARA" },
    { name: "Asturias", value: "AST" },
    { name: "Canarias", value: "CANA" },
    { name: "Cantabria", value: "CANT" },
    { name: "Castilla y la Mancha", value: "CASM" },
    { name: "Castilla y León", value: "CASL" },
    { name: "Cataluña", value: "CAT" },
    { name: "Extremadura", value: "EXT" },
    { name: "Galicia", value: "GAL" },
    { name: "Islas Baleares", value: "BAL" },
    { name: "La Rioja", value: "RIO" },
    { name: "Madrid", value: "MAD" },
    { name: "Murcia", value: "MUR" },
    { name: "Navarra", value: "NAV" },
    { name: "País Vasco", value: "PVA" },
    { name: "Valencia", value: "VAL" },
  ];